# Generated by Django 6.0 on 2026-01-09 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sysuser',
            options={'verbose_name': '系统用户', 'verbose_name_plural': '系统用户'},
        ),
        migrations.AddField(
            model_name='sysuser',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='是否活跃'),
        ),
        migrations.AddField(
            model_name='sysuser',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AlterField(
            model_name='sysuser',
            name='avatar',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='用户头像'),
        ),
        migrations.AlterField(
            model_name='sysuser',
            name='create_time',
            field=models.DateField(blank=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='sysuser',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='用户邮箱'),
        ),
        migrations.AlterField(
            model_name='sysuser',
            name='login_date',
            field=models.DateField(blank=True, null=True, verbose_name='最后登录时间'),
        ),
        migrations.AlterField(
            model_name='sysuser',
            name='password',
            field=models.CharField(max_length=255, verbose_name='密码'),
        ),
        migrations.AlterField(
            model_name='sysuser',
            name='phonenumber',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='手机号码'),
        ),
        migrations.AlterField(
            model_name='sysuser',
            name='remark',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='sysuser',
            name='status',
            field=models.IntegerField(default=0, verbose_name='帐号状态（0正常 1停用）'),
        ),
        migrations.AlterField(
            model_name='sysuser',
            name='update_time',
            field=models.DateField(blank=True, null=True, verbose_name='更新时间'),
        ),
    ]
