# Generated by Django 6.0 on 2026-01-14 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_sysuser_options_sysuser_is_active_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sysuser',
            options={'verbose_name': '系统用户', 'verbose_name_plural': '系统用户列表'},
        ),
    ]
