"""
Django settings for DjangoPermit project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-i0u9fcxf0v9^=p$h+xbw3trg61ac$p@ub-n+9np%ipb0_&)t0-'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost', '127.0.0.1']  # 开发环境允许的主机


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',  # CORS 跨域支持
    'user.apps.UserConfig',
    'menu.apps.MenuConfig',
    'role.apps.RoleConfig',
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # CORS 中间件（必须在 CommonMiddleware 之前）
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'user.middleware.JwtAuthenticationMiddleware',
]

ROOT_URLCONF = 'DjangoPermit.urls'



TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'DjangoPermit.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

#数据库要单独创建好之后再执行程序。
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': "db_admin",
        'USER': "hualj",
        'PASSWORD': "123456",
        'HOST': "127.0.0.1",
        'PORT': "3306",
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# 配置自定义用户模型
AUTH_USER_MODEL = 'user.SysUser'
# AUTH_USER_MODEL = 'user.SysUser'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}

from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1),  # Access token 的有效期为一天
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),  # Refresh token 的有效期为一周
    'ROTATE_REFRESH_TOKENS': False,  # 是否在登录时旋转 refresh tokens，默认是 False。设置为 True 可以提高安全性。
    'BLACKLIST_AFTER_ROTATION': False,  # 是否在旋转 refresh tokens 后将其加入黑名单，默认是 False。设置为 True 可以提高安全性。
    'UPDATE_LAST_LOGIN': False,  # 是否在登录时更新用户的最后登录时间，默认是 False。设置为 True 可以记录用户登录时间。
    'ALGORITHM': 'HS256',  # 签名算法，默认是 HS256。也可以使用其他算法如 RS256。
    'SIGNING_KEY': SECRET_KEY,  # 签名密钥，默认是 SECRET_KEY 设置的值。也可以自定义。
    'VERIFYING_KEY': None,  # 用于验证 token 的密钥，默认是 None。如果使用非对称加密算法，则需要设置。
    'AUDIENCE': None,  # 用于验证 token 的受众，默认是 None。如果需要验证 token 的受众，可以设置。
    'AUTH_HEADER_TYPES': ('Bearer',),  # 用于验证 token 的 HTTP 头部类型，默认是 ('Bearer',)。也可以添加其他类型如 'JWT'。
}

# ============================================
# CORS 跨域配置
# ============================================
# 开发环境：允许所有来源（仅用于开发，生产环境需要指定具体域名）
CORS_ALLOW_ALL_ORIGINS = True  # 开发环境设置为 True，生产环境应设置为 False

# 生产环境配置示例（开发时注释掉，生产时使用）：
# CORS_ALLOWED_ORIGINS = [
#     "http://localhost:8081",
#     "http://127.0.0.1:8081",
#     "https://yourdomain.com",  # 生产环境域名
# ]

# 允许的请求方法
CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

# 允许的请求头
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',  # 允许 JWT token
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# 允许携带凭证（cookies, authorization headers 等）
CORS_ALLOW_CREDENTIALS = True

# 预检请求的缓存时间（秒）
CORS_PREFLIGHT_MAX_AGE = 86400

MEDIA_ROOT = BASE_DIR / 'media'
MEDIA_URL = 'media/'